# config_TGCN.yaml

# Dataset preparation settings
random_seed: 42
dataset_dimension: '3D'  # "6D" or "3D"
dataset_name: 'UR5_v2'
dataset_type: 'grid'  # "random" or "grid"
num_joints: 6


locate_data_file: 'data/dfs_keyword.yaml'
prep_data_incl_past_residuals: False  # True or False
scalers_file: 'data/scalers.joblib'
adjacency_matrix_file: 'data/adjacency_matrix1.npy'

# Target pose variables for multi
target_pose_variables:
  6D:
    - x_t
    - y_t
    - z_t
    - rx_t
    - ry_t
    - rz_t
  3D:
  - x_t
  - y_t
  - z_t

# Pose residual variables for multi
residual_variables:
  6D:
    - x_dif
    - y_dif
    - z_dif
    - rx_dif
    - ry_dif
    - rz_dif
  3D:
  - x_dif
  - y_dif
  - z_dif

# Model parameters
model:
  hidden_dim: 128          # Hidden dimension in the TGCN cell 
  in_channels_6D: 6        # Number of features per node
  in_channels_3D: 3        # Number of features per node

# Training parameters
training:
  batch_size: 16
  num_epochs: 100
  learning_rate: 0.0001
  weight_decay: 0.01
  patience: 15           # For early stopping


# Device configuration
device: 'cpu'             # 'cuda' or 'cpu' or 'mps'

# model names
model_name:
  multi: 'TGCN'
